<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Cluster.Sharding"/>
    <PackageReference Include="Aaron.Akka.Reminders"/>
    <PackageReference Include="protobuf-net"/>
  </ItemGroup>

</Project>
